[variables]
PORT = "8000"

[phases.build]
cmds = [
  "pnpm install --frozen-lockfile",
  "pnpm run build"
]

[phases.start]
cmd = "pnpm start"

[phases.setup]
nixPkgs = ["nodejs-18_x", "nodePackages.pnpm"]

# Expose both SSH and HTTP ports
[phases.deploy]
ports = ["2222", "8000"]